version: '3.8'

services:
  # rinha-go:
  #   container_name: rinha-go
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - postgres

  postgres:
    container_name: postgres
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - postgres
